# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a839f8a1e1b65dc72dc0a228e69be1a93cbc41c5420ac15742d315d61b58f20df7df1b2e704e4fa03fdaeded3871b44359b72c924f562b83a2f5c5228e5bfadb

test:
  secret_key_base: aa4646a1c79e7554b8f1d47912552b56c767e6085e84b13b75666652084f43d516261244c97e4f7db9560a993386680ed3291e932ded9399be5b10c3b4af39e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
