# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 361213ad2f33348e9edb9545bff62555bc8be9902c453f80f7d534219fcbebbfe21f171c57b41b89b5b0c344eab578c6942a7555f2108a2af355be37819e2e09

test:
  secret_key_base: 2f54d392099d50da119883fdaef8e4deb6fc14312bd387ed30d973585f8a1ca8ca7bdedcce22b1613266dd274507e6cf37cd57e5251a129eeff47f4de3a7be40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
