# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb77ea481d79be93d0630519234ee7bbc1631735fd9bb4a5a9ae63cb45d4f35834f12842c8119dec81fbfdc882814a9ad1a6f7221e48828845118e2f0b25150

test:
  secret_key_base: 2041b4f23f4895b0fd8ed94f04f9f22f7c92b72dff986379755e37b833d864f310525a796ea186e0afed82152f252e3da68a4883e6afb1916fa6ba4499406ee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
